### ISSUE TITLE
Add default language to Cucumber runner builder

### ISSUE THREAD

**Issue by bbqsrc** [cucumber-rs/cucumber#102]
Should be possible to set the default language from the builder.

**Comment by tyranron** [comment]
Now possible with `Cucumber::language()` after merging #128

@ilslv again, we should provide a meaningful example in the Book.

**Comment by tyranron** [comment]
Described in ["Features" chapter of the Book](https://cucumber-rs.github.io/cucumber/main/Features.html#spoken-languages).
