### ISSUE TITLE
Add default matching tags to Cucumber runner builder

### ISSUE THREAD

**Issue by bbqsrc** [cucumber-rs/cucumber#103]
Sharing feature files amongst several projects means that only some of the features need to be tested in some codebases. One mechanism for managing this is tags, so one can filter out those scenarios that are to be ignored.

We should be able to specify the default tags in the builder so they don't need to be hacked in somewhere else.

**Comment by tyranron** [comment]
Can be done by `Cucumber::filter_run_and_exit()` after merging #128

@ilslv let's describe this in the Book too.

**Comment by tyranron** [comment]
Described in documentation for `Cucumber::filter_run_and_exit()`, and mentioned in ["Managing growth" chapter of the Book](https://cucumber-rs.github.io/cucumber/main/Test_Modules_Organization.html#managing-growth).
