### ISSUE TITLE
Generate Default Steps If None Exist

### ISSUE THREAD

**Issue by tscritch** [cucumber-rs/cucumber#106]
If this feature already exists I apologize, but I can't seem to find it if it does.

I would like cucumber to output (whether in the console or a file) a default steps implementation if the scenario steps cannot be found but there is an existing feature file. I know other versions of cucumber do this for other languages/testing frameworks.
 
My guess is that this would be fairly straightforward given we have the feature file parsed and can generate a basic/empty steps builder. I would love to contribute this feature if it is something wanted. 

`example.feature`
```feature
Feature: Example feature
  Scenario: An example scenario
    Given I am trying out Cucumber
    When I consider what I am doing
    Then I am interested in ATDD
    And we can implement rules with regex
```

output (something like this):
```rust
let mut builder: Steps<crate::MyWorld> = Steps::new();

builder
  .given_async(
      "I am trying out Cucumber",
      t!(|mut world, _step| {
          world
      })
  )
  .when_regex_async(
      "I consider what I am doing",
      t!(|world, _matches, _step| {
          world
      }),
  )
  .then("I am interested in ATDD", 
      t!(|world, _step| {
          world
      })
  )
  .then("we can implement rules with regex",
      t!(|world, _step| {
          world
      })
  );
```

**Comment by bbqsrc** [comment]
Hey! It is not yet something that exists, and I am aware of what other languages do. It's a neat feature, but I've always felt it... wasn't enough.

My more ambitious plan is to use a Cucumber-aware extension to the language server to allow autocompleting steps based on feature files. This is one reason I wrote the gherkin crate, so I had control over the AST to enable this. :smile:

But that's a while off. I'd be happy to accept a PR that implements something like this in the interim if you have a good proposal on how to go about it.

**Comment by GoooIce** [comment]
The vscode cucumber plugin now supports https://github.com/cucumber/vscode

**Comment by tyranron** [comment]
I guess we can close this now. Despite being [a controversial feature](https://github.com/cucumber-rs/cucumber/issues/106#issuecomment-948560104), it really feels like a responsibility of external tooling, rather than Cucumber itself.

Feel free to reopen, if there will be much demand of this.
