### ISSUE TITLE
Fixture support as 1st class citizen

### ISSUE THREAD

**Issue by bbros-dev** [cucumber-rs/cucumber#120]
Would be nice to have support for fixtures as first class citizen.

Below are specifications what functionality those features might provide, obviously adapted to Rust conventions:

https://relishapp.com/cucumber/aruba/v/0-11-0/docs/filesystem/use-a-fixture

**Comment by tyranron** [comment]
@bbros-dev could you explain this a little bit better. From the description and the link it's not obvious enough for me to understand how this should look like and work.

It would be nice if you provide a better explanation along with code snippets of how this should work.

**Comment by bbros-dev** [comment]
@tyranron my understanding is that Aruba is out of scope for Cucumber, so closing.  Reopen if that understanding is incorrect and I'll elaborate.
