### ISSUE TITLE
Option to only show failed and/or skipped scenarios

### ISSUE THREAD

**Issue by damoon** [cucumber-rs/cucumber#129]
after only adding (what feels to me like) only a few tests the output becomes overwhelming.
it would be nice to have the option to hide all the successful tests and focus on the failing or not yet implemented tests.

**Comment by tyranron** [comment]
Resolved in #133, mentioned in the Book, and documented in Rust docs with examples.

**Comment by cfstras** [comment]
While I love cucumber-rs, it's annoying to always print every single passed scenario. Is there an option to not just repeat failed tests, but **also completely hide** passed tests?

Or do I have to implement a custom writer to accomplish this?
Thanks :)

**Comment by ilslv** [comment]
@cfstras due to streaming nature of our basic `Writer`: print `Step`s as they are available, we don't have the knowledge, whether `Scenario` is failed or not. You'll have to implement custom `Writer` with some buffer, that will write out the whole `Scenario`, once `Step` fails.
