### ISSUE TITLE
This repo's example does not work with rust: syntex_syntax error `cx.parse_sess.span_diagnostic` as immutable because it is also borrowed as mutable

### ISSUE THREAD

**Issue by darrow-olykos** [cucumber-rs/cucumber#138]
Given rust version is 1.55
And the example is copied from this repo documentation

When "cargo test" is executed
Then tests should pass

Instead, this error occurs:
```
cargo test
     Compiling syntex_syntax v0.39.0
     error[E0502]: cannot borrow `cx.parse_sess.span_diagnostic` as immutable because it is also borrowed as mutable
```

Does this mean this `cucumber` crate is currently incompatible with rust v1.55?

**Comment by darrow-olykos** [comment]
@ilslv I used docs from `edge` book because `current` link shows 404 pages.
The Cargo.toml on edge uses 0.10.0.

Using `cucumber = { git = "https://github.com/cucumber-rs/cucumber/" }` works 👍 ✅ 

Thank you

**Comment by darrow-olykos** [comment]
Should this issue remain open until the crate published to crates.io is compatible with this version of rust?
That version is "0.3.1" and that also causes [this error](https://github.com/cucumber-rs/cucumber/issues/138#issue-1021907145)

**Comment by ilslv** [comment]
@darrow-olykos it's ok to leave it closed I guess.

But I'll look into a way to automatically use `cucumber = { git = "https://github.com/cucumber-rs/cucumber/" }` or `cucumber = 0.10` depending on which book (edge or current) you are currently viewing.
