### ISSUE TITLE
Fail to parse feature when template are touching each other

### ISSUE THREAD

**Issue by FirelightFlagboy** [cucumber-rs/cucumber#161]
## Context

Given the following scenario

```gherkin
Feature: Test touching template
  Scenario Outline: test template
    Given The name <Left><Right>
    Then The name is <Full>

    Examples:
      | Left | Right | Full   |
      | Foo  | Bar   | FooBar |
```

I'm getting the following error

```
Failed to parse: Failed to expand examples: Failed to resolve <Left><Right>
```

The error is present on the following version:
- ab430cc (current `main` at the time)
- `0.10.2`

## How to replicate

```sh
git clone --depth 1 git@github.com:cucumber-rs/cucumber.git
cd cucumber
cat << EOF | tee tests/features/wait/template.feature
Feature: Test touching template
  Scenario Outline: test template
    Given The name <Left><Right>
    Then The name is <Full>

    Examples:
      | Left | Right | Full   |
      | Foo  | Bar   | FooBar |
EOF
cargo test
```

## What I'm expecting

I'm expecting the Feature to be correctly parsed

**Comment by ilslv** [comment]
@FirelightFlagboy I've looked through all test cases and issues across all implementations and couldn't find usecases like this. This means I'm not sure whether this should be considered as a parsing error or not, as `Gherkin` doesn't have strict grammar and compatibility is defined through being compliant with [official test kit][1].

I'll leave this issue open, but I don't think it will be resolved anytime soon. 




[1]: https://github.com/cucumber/common/tree/main/compatibility-kit

**Comment by tyranron** [comment]
@ilslv is the problem source in `gherkin` parser?

**Comment by ilslv** [comment]
@tyranron @FirelightFlagboy never mind, this issue appears because of `<(\S+)>` regex in `feature::Ext` trait impl. Regex should be `<([^>]+)>`

**Comment by tyranron** [comment]
@FirelightFlagboy thanks for the report 🍻

**Comment by FirelightFlagboy** [comment]
Thanks for the fix :)
