### ISSUE TITLE
Issue with `resolver` feature that requires nightly.

### ISSUE THREAD

**Issue by johnoneil** [cucumber-rs/cucumber#167]
I'm trying to move from the older `cucumber_rust` crate to this crate but running into an issue with a nightly feature being required in the `sealed ` crate.

To reproduce, I simply add the following (ignoring ellipses) to my `Cargo.toml`, and no further code.
```
[dependencies]
...
"cucumber" = "0.10.2"
```
Rust and Cargo versions on linux:
```
rustc 1.50.0 (cb75ad5db 2021-02-10)
cargo 1.50.0 (f04e7fab7 2021-02-04)
```

Get the following error
```
error: failed to download `sealed v0.3.0`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/home/joneil/.cargo/registry/src/github.com-1ecc6299db9ec823/sealed-0.3.0/Cargo.toml`

Caused by:
  feature `resolver` is required

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can add
  `cargo-features = ["resolver"]` to enable this feature

```

I don't see anything in the  `README.md` in this repo that says nightly is required, so is this just an oversight? Can it be fixed by manipulating features?
Can't really look at this again for a while.

**Comment by ilslv** [comment]
@johnoneil 

> I don't see anything in the README.md in this repo that says nightly is require

Nightly isn't actually required, but `README.md` has badge about minimum supported Rust version, which is `1.56`.
