### ISSUE TITLE
Allow scenario expansion for docstrings

### ISSUE THREAD

**Issue by rogertorres** [cucumber-rs/cucumber#172]
The scenario expansion currently replaces templates from both the step and its table.

https://github.com/cucumber-rs/cucumber/blob/e7387d469502dcc6286a5ef24204d33fc0d198e3/src/feature.rs#L158-L162

Do you think it is possible to add the step docstring into the mix? This would allow us to validate docstrings that are slightly different from one another in a single scenario.

**Comment by tyranron** [comment]
@rogertorres could you provide a little bit wider example of such scenario and the code you do want in a step matching function?

**Comment by rogertorres** [comment]
hey @tyranron, please consider the simplified example below:

```gherkin
Feature: Doc String expansion
    Scenario Outline: Counting Song
        Given I have a file with the "Ants Go Marching" song
        When I read the <nth> paragraph
        Then I should sing:
        """
        The ants go marching <number> by <number>
        The little one stops to <action>
        """
        
        Examples:
            | nth     | number | action         |
            | first   | one    | suck his thumb |
            | second  | two    | tie his shoe   |
            | third   | three  | climb a three  |
            | fourth  | four   | shut the door  |
```

The example's idea is to be able to replace `<number>` and `<action>`. In Rust, I would read the actual file and check if its paragraphs match the docstring expanded with the examples.

IRL, such feature would allow us to validate contents that are not structured, such as human-readable logs generated by other tools, making the docstring usage a bit more flexible. The alternative I have today is to use the Examples/Data-Table variables to build this docstring inside Rust, but then my Gherkin file becomes less expressive.

**Comment by tyranron** [comment]
@rogertorres thanks! Seems quite reasonable.

cc @ilslv 

Let's add it to upcoming 0.11 release.
