### ISSUE TITLE
cannot infer type for type parameter `T` declared on the trait `AsRef`

### ISSUE THREAD

**Issue by Zylatis** [cucumber-rs/cucumber#173]
Hi there,

Just trying to compile and run the example in the book but i am getting the following
```
cargo test --test example                                                                                                                                                                                            
    Blocking waiting for file lock on build directory
   Compiling cucumber v0.10.2
error[E0282]: type annotations needed
   --> /home/graeme/.cargo/registry/src/github.com-1ecc6299db9ec823/cucumber-0.10.2/src/feature.rs:133:10
    |
131 |       let (header, vals) = match scenario
    |  ________________________________-
132 | |         .examples
133 | |         .as_ref()
    | |__________^^^^^^_- this method call resolves to `&T`
    |            |
    |            cannot infer type for type parameter `T` declared on the trait `AsRef`
    |
    = note: type must be known at this point

For more information about this error, try `rustc --explain E0282`.
error: could not compile `cucumber` due to previous error
```

And the project setup looks like this
![example](https://user-images.githubusercontent.com/1456631/144337810-7039f418-9928-432c-968c-7b06d8befa98.png)

I feel like probably i'm missing something simple? I tried with rust 2021 too just in case, no dice. I also notice this `match` is not present in the current version of the code here?

Thanks,
Z

EDIT: Sorry should also say, on Ubuntu 20.04 with `rustc 1.56.1 (59eed8a2a 2021-11-01)`

**Comment by ilslv** [comment]
@tyranron it looks like we should have released `gherkin` under `0.11`, because changing `Examples` from `Option` to `Vec` is a breaking change and leads to this error. 

@Zylatis you have couple of options:
- just wait couple of days for a new `cucumber` release
- downgrade `gherkin` crate to `10.1`
- use git dependency on `main` branch of this repo as this issue is already resolved there

**Comment by Zylatis** [comment]
Perfect, works now - thanks!

**Comment by tyranron** [comment]
@ilslv yup, that was unfortunate. 😕

But let's just land `0.11` release of `cucumber` and do yank `gherkin` only if more people will hit into it

**Comment by tyranron** [comment]
@Zylatis we've [yanked](https://doc.rust-lang.org/cargo/commands/cargo-yank.html) `0.10.2` version of `gherkin_rust`, so if you recreate your `Cargo.lock` this won't appear anymore.

Sorry for the incovenience.
