### ISSUE TITLE
println! in steps is not working as expected.

### ISSUE THREAD

**Issue by antonkol** [cucumber-rs/cucumber#177]
i have few println! inside steps and when i am executing tests information in println! appears before all Cucumber log.

Something like this:
```
some info 1
some info 2

 Feature: Some feature
   Scenario Outline: Some scenario outline
       Given
       And
   Scenario Outline: Some scenario outline
      Given
       And
```

Is there a way to output println! below appropriate step ?

Something like this:
```
 Feature: Some feature
   Scenario Outline: Some scenario outline
       Given
          some info 1
       And
   Scenario Outline: Some scenario outline
      Given
          some info 2
       And
```

**Comment by ilslv** [comment]
@antonkol unfortunately this is feature isn't supported. The main reason behind it is a concurrent `Scenario` execution. So to support this feature we somehow need to come up with mechanism to intercept output of the `println!` macro, somehow understand which step it belongs to from the context of the `Step` function, store all this data and only when the time is right output it. 
Maybe this is possible with custom `println!` and `dbg!` macros, but I believe that it's not possible with default ones. 

I'll leave this issue open with a `rfc` tag and give it a thought a bit more.

**Comment by tyranron** [comment]
@ilslv may be a clear explanation of how to run tests, so the custom output will appear naturally, will do the job?

Is `--concurrency=1` will be enough? Or we should also remove `writer::Normalized` from pipeline? Could you provide an example? I'll include the one to the Book in #171.

**Comment by ilslv** [comment]
@tyranron 

> Is --concurrency=1 will be enough? Or we should also remove writer::Normalized from pipeline?

To achieve natural output, you'll need to do the following steps:
1. Create `writer::Basic::raw` with `Coloring::Never` to avoid interference with pretty-printed output
```rust
writer::Basic::raw(stdout(), writer::Coloring::Never, false)
    .summarized()
```
2. You'll need custom `Writer` like `AssertNormalized` which implements `Normalized` for any `Writer`, but does nothing. This isn't supplied by crate yet, but maybe we should?
3. Set `max_concurrent_scenarios()` to `1`

Full example:

```rust
let res = World::cucumber()
    .max_concurrent_scenarios(1)
    .with_writer(writer::AssertNormalized(
//                       ^^^^^^^^^^^^^^^^ doesn't exist yet. 
        writer::Basic::raw(stdout(), writer::Coloring::Never, false)
            .summarized(),
    ))
    .with_cli(cli)
    .run_and_exit("tests/features/wait");
``` 

Output for `wait` test with `dbg!` and all steps above

```
Feature: Basic
  Scenario: 1 sec
[tests/wait.rs:61] world.0 = 1
   ✔> Given 1 sec
[tests/wait.rs:61] world.0 = 2
   ✔  Given 1 sec
[tests/wait.rs:61] world.0 = 3
   ✔  When 1 sec
   ?  Then unknown
      Step skipped: /Users/work/Work/cucumber/tests/features/wait/rule.feature:9:5
...
```

**Comment by tyranron** [comment]
@ilslv 

> So even with all those steps we first see output of the dbg! and only then step result.

It's not a problem though, as we have them close to the performed step.

> 2\. You'll need custom `Writer` like `AssertNormalized` which implements `Normalized` for any `Writer`, but does nothing. This isn't supplied by crate yet, but maybe we should?

Hmmm, I think we should add them, along with ext-helpers, so we have:
```rust
let res = World::cucumber()
    .max_concurrent_scenarios(1)
    .with_writer(
        writer::Basic::raw(stdout(), writer::Coloring::Never, false)
            .summarized()
            .assert_normalized(),
    )
    .with_cli(cli) // do we really need this line here? It should work without it.
    .run_and_exit("tests/features/wait");
```

**Comment by ilslv** [comment]
@tyranron 

> `.with_cli(cli) // do we really need this line here? It should work without it.`

Oh, of corse no, left it by mistake 

> Hmmm, I think we should add them, along with ext-helpers, so we have:

Ok

**Comment by tyranron** [comment]
Done. Now it's only left to describe in new Book in #171.

**Comment by tyranron** [comment]
> Now it's only left to describe in new Book in #171.

Done.
