### ISSUE TITLE
Serial execution without modifying feature files?

### ISSUE THREAD

**Issue by ivanschuetz** [cucumber-rs/cucumber#184]
The features I'm executing (https://github.com/algorand/algorand-sdk-testing/tree/master/features/integration) have to be serial. 
Adding the `@serial` tag there is difficult, as it's used by 5+ other SDKs (langs) and it appears not to be part of the official specification (?). Would it be possible to configure this in code somehow?

**Comment by tyranron** [comment]
@ivanschuetz yup.

- Either use [`.max_concurrent_scenarios(1)`](https://docs.rs/cucumber/latest/cucumber/runner/basic/struct.Basic.html#method.max_concurrent_scenarios) when you constructing `Cucumber` as [shown here](https://github.com/cucumber-rs/cucumber/issues/177#issuecomment-988513310).

- Or just specify `--concurrency=1` CLI option like the following:
    ```bash
    cargo test --test my_tests -- --concurrency=1
    ```

This topic will be covered better in [new Book for `0.11` release](https://github.com/cucumber-rs/cucumber/pull/171), which, I hope, we will land soon. At the moment you may read [temporary version](https://github.com/cucumber-rs/cucumber/blob/755d59121655bca4a1eae9b0acdef2dc72590cf6/book/src/writing/tags.md#isolated-execution).

Hope, this helps.
