### ISSUE TITLE
README examples confusing

### ISSUE THREAD

**Issue by johnoneil** [cucumber-rs/cucumber#190]
I'm trying to move from the old `cucumber_rust` crate to `cucumber` as is recommended but am very confused by the initial `README` and implementation of new template based rules.

First, even though a similar `.feature` file is present in the examples, there is no similar test code within the crate. So these examples seem only notional to me.

I'll mention each case individually:

```
#[given(regex = r"^(\S+) is hungry$")]
async fn someone_is_hungry(w: &mut World, user: String) {
   sleep(Duration::from_secs(2)).await;
   
   w.user = Some(user);
}
```

I assume that since `(\S+)` captures, it is tied to the argument `user`. Is this correct?

Next:
```
#[when(regex = r"^(?:he|she|they) eats? (\d+) cucumbers?$")]
async fn eat_cucumbers(w: &mut World, count: usize) {
   sleep(Duration::from_secs(2)).await;

   w.capacity += count;
   
   assert!(w.capacity < 4, "{} exploded!", w.user.as_ref().unwrap());
}
```

Here both `(?:he|she|they)` and `((\d+) ` capture, but only one argument `count` is provided, and it maps to the 2nd capture. Is this correct?

Lastly:

```
#[then(regex = r"^(?:he|she|they) (?:is|are) full$")]
async fn is_full(w: &mut World) {
   sleep(Duration::from_secs(2)).await;

   assert_eq!(w.capacity, 3, "{} isn't full!", w.user.as_ref().unwrap());
}
```
Again there are two captures, but here no additional variables are provided in the async fn. How are the captures passed here?

Thanks for any input you can provide.

**Comment by eggyal** [comment]
`?:` at the start of a group means that it's non-capturing.  See https://docs.rs/regex/latest/regex/#grouping-and-flags

**Comment by johnoneil** [comment]
Thanks for your help. I've made the transition to the newer syntax, but am running into some issues building on rust 1.57.0 (`syntex_syntax` related). Our use case is probably a bit complex so I can't easily discern if we're using the crate properly.
Going to drop it for now and see how this develops over the next few months.
