### ISSUE TITLE
Command line option to disable printing `World` when there are failed tests or panics

### ISSUE THREAD

**Issue by yds12** [cucumber-rs/cucumber#192]
Hello,

First of all, thanks for the work on this awesome crate.

If I understand correctly, currently there is no way to disable printing the `World` in error messages. Whenever there is a failed test or panic, the whole `World` struct is printed. In some use cases this object can be quite large, making the errors difficult to navigate.

Would it be possible to add a command line flag that controls this behaviour?

**Comment by tyranron** [comment]
cc @ilslv  
Let's do this as `writer::Basic`'s CLI option and `pub` method before 0.11 release.

**Comment by tyranron** [comment]
@ilslv also, I think it's worth to bind it to the exisiting `verbosity` CLI option, so by default world is not printed, but with `--verbose` yes. What do you say?

**Comment by ilslv** [comment]
@tyranron I would split them, because I think that default behaviour should be "print failed world, but not the docstring". One reason for that is I saw some of users of this crate using docstrings as some kind of spec, [including graphql query there for example](https://github.com/cucumber-rs/cucumber/issues/56)

**Comment by tyranron** [comment]
@ilslv what about verbosity levels? `-v` prints world and `-vv` prints doc strings?

**Comment by ilslv** [comment]
@tyranron good idea 👍. I don't think there will be a case when someone wants to print docstrings, but not the world.

**Comment by tyranron** [comment]
@ilslv so, let's do it this way.

**Comment by theredfish** [comment]
If there is no verbosity option passed, nothing will be printed? Or will you add a default option?

**Comment by ilslv** [comment]
@tyranron 

> what about verbosity levels? -v prints world and -vv prints doc strings?

I believe that by default we should print `World` and problem this verbosity flag is that we can set `-v` by default, but there is no way to downgrade from here. We can make `-v` do nothing, `-vv` print `World` (and be default one), `-vvv` print both `World` and docstrings, but I'me sure this is idiomatic approach for verbosity flags. So I would stick with additional `bool` flag.

**Comment by tyranron** [comment]
@ilslv why not just `-v 0`, `-v 1`, `-v 2` with a `-v` implied `-v 1` by default?

**Comment by ilslv** [comment]
@yds12 @theredfish what do you think should happen _by default_ on failed `Step`s: printing `World` or not?

**Comment by yds12** [comment]
@ilslv I would say not by default.

**Comment by theredfish** [comment]
I see printing the `World` as extra debug info, that I would prefer to opt-in if I need it. I think that the assertion message on failed `Step`s is enough as a default behavior - then if I need to debug more I can re-run failed tests with the `World` output.
