### ISSUE TITLE
Inventory is no longer maintained

### ISSUE THREAD

**Issue by bbqsrc** [cucumber-rs/cucumber#206]
- https://github.com/dtolnay/inventory is archived
- https://github.com/rust-lang/rust/issues/47384#issuecomment-1022913071 asks why this is the case, on the issue that indicates why it is likely to be the case.

This may impact Cucumber.

**Comment by tyranron** [comment]
Ideally, we'll be able to remove `inventory` for our purposes, once `&mut` is allowed in `const`, so we can create a "global registry" in compile time by ourselves.

At the moment, however, it's better to look how the situation evolves, as with archiving that projects we have no similar solutions in the ecosystem.

**Comment by tyranron** [comment]
Not deprecated anymore: https://github.com/dtolnay/inventory/issues/32#issuecomment-1171550940
