### ISSUE TITLE
Cargo command doesn't fail on skipped step if executed with retries

### ISSUE THREAD

**Issue by serzhshakur** [cucumber-rs/cucumber#249]
The `cargo test` command doesn't fail on skipped steps if ran with retries (see picture)

Checkout [this repo](https://github.com/serzhshakur/yace)

The command `cargo test --test example -- -n="fail on skipped"` will fail with exit code 101
However `cargo test --test example -- -n="fail on skipped" --retry=1` will exit with status code 0

Also short summary doesn't mention anything about failing tests.

![cucumber__fail_on_skipped](https://user-images.githubusercontent.com/15928203/205310564-22834a34-501a-4b12-bfc9-1eeaf969e52a.png)

**Comment by tyranron** [comment]
@serzhshakur thanks!

@ilslv it seems that runner finishes before the test is retried. Could you look into it?   
It's also not the first time when [something like this happens](https://github.com/cucumber-rs/cucumber/issues/241) (it may be a related bug). We definitely need a rich set of test cases for features combinations (now we test them mostly separately), maybe as a separate PR.

**Comment by tyranron** [comment]
@serzhshakur fixed in #250, released in [0.18.0](https://github.com/cucumber-rs/cucumber/releases/tag/v0.18.0).

**Comment by serzhshakur** [comment]
thank you so much!
