### ISSUE TITLE
Scenarios without implemented steps should fail

### ISSUE THREAD

**Issue by jorgecarleitao** [cucumber-rs/cucumber#254]
Hi,

I noticed that when a scenario is missing a step, it is skipped and `cargo test` yields exit 0.

IMO this is a bit surprising and a bug - imo when an implementation of a test is missing, the test harness should error. The developer may wish to use an empty test or a `todo!` on the code, but not erroring makes it likely that people will ignore an example.

**Comment by ilslv** [comment]
@jorgecarleitao this is not a bug, but a desired behaviour. In case you want skipped steps to fail [use `Cucumber::fail_on_skipped()`](https://cucumber-rs.github.io/cucumber/main/writing/tags.html#failing-on-skipped-steps).

**Comment by jorgecarleitao** [comment]
Interesting. Python's `behave` fails on unimplemented steps, which I regarded as a guard rail against missed steps resulting in skipped but not failed tests.

But fair enough, it is not specified what the default behavior should be, so this behavior can also be considered desirable.

Thanks for the reply and for this awesome library.
