### ISSUE TITLE
Scenarios or steps with escaped quotes in names aren't rendered properly by IntelliJ

### ISSUE THREAD

**Issue by gbemiga-viewserver** [cucumber-rs/cucumber#269]
Spent a fair few hours working out why I couldn't see output in the intellij test runner as I would expect. The issue seems to be that if you use the expr attribute (rather than regex) in your step definitions the lib test output breaks and you just see a stream of json outputted to console rather than the correct test runner output.

This doesn't work (i.e runs but won't show output in intellij test runner)
#[when(expr = "server {string} connects to server {string}")] 

This does work
#[when(regex = "server (\w+) connects to server (\w+)")] 

Happy to look at it if it's not already on your radar and if you can confirm that it's not just me doing something really silly :D

**Comment by gbemiga-viewserver** [comment]
I've created a PR to show the issue https://github.com/cucumber-rs/cucumber/pull/270/
I think the issue is the {string} token {u64} seems to work fine 
You'll notice strangely the tests are all running as expected in the background just outputting JSON and not to libtest as expected.
Again totally open to this just being an issue with my usage not with the framework. 
Am also willing to help fix if you need (assuming that there is actually an issue)

**Comment by ilslv** [comment]
@gbemiga-viewserver thanks for the report. Actually the problem is on the IntelliJ side and have nothing to do with this crate. [I've filed an issue for it](https://github.com/intellij-rust/intellij-rust/issues/10310).
