### ISSUE TITLE
Neither feature nor scenario headings are printed after updating to 0.20

### ISSUE THREAD

**Issue by serzhshakur** [cucumber-rs/cucumber#299]
After updating to cucumber-rs 0.20 neither feature, nor scenario, nor rule headings are printed to a console when running tests with colored output. See the comparison below:
- with cucumber-rs **0.19**
  ![image](https://github.com/cucumber-rs/cucumber/assets/15928203/ba239983-bb5b-4408-92e3-1c390c699403)

- with cucumber-rs **0.20**
  ![image](https://github.com/cucumber-rs/cucumber/assets/15928203/fe8cc0a2-5921-4779-b071-bc56bf763130)

However heading are printed when running tests with `--color=never`

![image](https://github.com/cucumber-rs/cucumber/assets/15928203/1a90910d-8e99-4690-9e0b-55204afcbdf4)

You can check [this repo](https://github.com/serzhshakur/yace/tree/cucumber-rs-0.20) for the reference

**Comment by serzhshakur** [comment]
Probably related to https://github.com/cucumber-rs/cucumber/issues/282

**Comment by zohnannor** [comment]
I've bisected the commits between  https://github.com/cucumber-rs/cucumber/releases/tag/v0.20.0 and https://github.com/cucumber-rs/cucumber/releases/tag/v0.19.0. [This](https://github.com/cucumber-rs/cucumber/commit/a091bb22d1ce6de518570e3d8fc1c603b01a88da#diff-6f78dd25da56c0310a1f1e2d066739a6b63f93d87e3becd2124b4797a95804b7R553
) and [this](https://github.com/cucumber-rs/cucumber/commit/a091bb22d1ce6de518570e3d8fc1c603b01a88da#diff-6f78dd25da56c0310a1f1e2d066739a6b63f93d87e3becd2124b4797a95804b7R828) are changes (introduced in #258) that seem to cause the new, wrong behavior. As I don't know the exact reasoning behind those changes, I'll ping @ilslv for elaboration/investigation :slightly_smiling_face:

**Comment by berkes** [comment]
Probably related: [tracing](https://cucumber-rs.github.io/cucumber/current/output/tracing.html) output gets overwritten by this same "bug" it seems. Disabling color keeps the tracing output, enabling color overwrites it with blank lines.

**Comment by tyranron** [comment]
@serzhshakur @berkes released as [0.20.1](https://crates.io/crates/cucumber/0.20.1).

**Comment by serzhshakur** [comment]
Great, thank you, works as expected now 👍
