### ISSUE TITLE
Cucumber ran as library traps over CLI arguments

### ISSUE THREAD

**Issue by raffaeleragni** [cucumber-rs/cucumber#303]
I am trying to wrap my own CLI args to extend some extra features, run multiple instances of cucumber, and potentially do also more.
I am using clap for my own args, but the problem is as soon as I run cucumber, it also tries to parse the arguments using its own clap defined parser and will stop working saying that arguments are invalid.

Example:

```rust
use clap::Parser;
use cucumber::World;

#[derive(World, Debug, Default)]
struct Env;

#[derive(Parser, Debug)]
#[command()]
pub struct Args {
    pub targets: Vec<String>,
    #[arg(long)]
    pub serial: bool,
}

#[tokio::main]
async fn main() {
    let args = Args::parse();
    for target in args.targets {
        Env::run(target).await;
    }
}
```

`./target/debug/test_cuc --serial main.feature`

```
error: unexpected argument '--serial' found

Usage: test_cuc [OPTIONS]

For more information, try '--help'.
```

I noticed it happens around this place: https://github.com/cucumber-rs/cucumber/blob/main/src/cucumber.rs#L732
Would it be possible to make the that cli parser optional in some way?

**Comment by tyranron** [comment]
@raffaeleragni yes, of course.

This is described in [this chapter of the Book](https://cucumber-rs.github.io/cucumber/current/cli.html#customizing). And also answered here: https://github.com/cucumber-rs/cucumber/discussions/294#discussioncomment-6435194.

**Comment by ilslv** [comment]
there is a [separate book chapter](https://cucumber-rs.github.io/cucumber/current/cli.html) describing how to achieve this
