### ISSUE TITLE
Book example not working 

### ISSUE THREAD

**Issue by bq-wrongway** [cucumber-rs/cucumber#305]
I was checking out this example https://cucumber-rs.github.io/cucumber/current/writing/scenario_outline.html

And it does not compile (well, unless i remove .await) keywords.

```
error[E0277]: `()` is not a future
  --> tests/example.rs:23:35
   |
23 |     sleep(Duration::from_secs(2)).await;
   |     ------------------------------^^^^^
   |     |                            ||
   |     |                            |`()` is not a future
   |     |                            help: remove the `.await`
   |     this call returns `()`
   |
   = help: the trait `futures::Future` is not implemented for `()`
   = note: () must be a future or must implement `IntoFuture` to be awaited
   = note: required for `()` to implement `std::future::IntoFuture`
```

Am i doing something wrong or the example is missing something ?

**Comment by ilslv** [comment]
you are probably using [`std::thread::sleep()`](https://doc.rust-lang.org/stable/std/thread/fn.sleep.html) instead of the [`tokio::time::sleep()`](https://docs.rs/tokio/latest/tokio/time/fn.sleep.html)
