### ISSUE TITLE
`cargo test` does not detect main functions

### ISSUE THREAD

**Issue by bachrc** [cucumber-rs/cucumber#312]
In the official documentation, the recommended way to add a test is to make a `example.rs` test, and to do a `main()` function with either `futures` or a `#[tokio::main]` to contains the `World::run`.

Though, this method is not detected when doing `cargo test --test example`. Because it only detects methods annotated with ` #[test]`, examples everywhere in the documentation does not work, unless the method is annotated with `#[tokio::test]`

**Comment by tyranron** [comment]
@bachrc it always worked for us. Didn't you miss
```toml
[[test]]
name = "example"
harness = false
```
in your `Cargo.toml`?

**Comment by bachrc** [comment]
Yup! I have a simple workspace which contains the `integration_tests` member.

This crate has this [[test]] section. So when I launch `cargo test -p integration_tests --test example`, it doesn't detect any test in my `integration_tests/tests/example.rs`. Unless I annotate with `#[tokio::test]`

**Comment by bachrc** [comment]
I am sorry for making you lose some time, this was a shitty mistake on my end...

I wrote `[[tests]]` in my Cargo.toml file, and not `[[test]]`... works way better now. Thank you for your wonderful library, please have a nice day
