### ISSUE TITLE
Sharing state across scenarios

### ISSUE THREAD

**Issue by guenhter** [cucumber-rs/cucumber#348]
Hi,

I have a lot of scenarios which are working with a docker testcontainer. Each scenario starts up the container and when the world is dropped, the container is also stopping. When a new world is created, a new  container is created. This works fine, but it is slow. I'd appreciate if the container could be started like this:

```rust
fn main() {
    let container = startContainer();
    MyWorld::cucumber()
            .fail_on_skipped()
            .add_state(container) // don't nail me on this. Just here to see what I mean
            .run_and_exit("tests/features/user/")
            .await;
    // Container gets stopped when main is exited.
}
```

When the world is then created, I'd need some way to access the container (e.g. for getting out the correct ports).

What do you think about this?

**Comment by tyranron** [comment]
@guehnter If you need multiple `World`s to share the same global state, there is no specific API for this in `cucumber`. However, nothing prevents you from communicating via some global variable or other global mechanism.

For example:
```rust
static CONTAINER: LazyLock<Container> = LazyLock::new();

fn main() {
    CONTAINER.set(startContainer()).unwrap();
    MyWorld::cucumber()
            .fail_on_skipped()
            .run_and_exit("tests/features/user/")
            .await;
    CONTAINER.stop();
}
```

And you can access `CONTAINER` either directly in your step matchers, or put it into the `MyWorld` during its initialization.

**Comment by tyranron** [comment]
Of course, some API for global state could have been baked in. However, giving the situation is quite rare and solving it isn't a huge pain-in-the-ass, I doubt it's worth complication of the machinery.
