### ISSUE TITLE
Please clarify: type of table cells

### ISSUE THREAD

**Issue by pcn** [cucumber-rs/cucumber#55]
There is an example of tables, but the example infers the type from cucumber's step, and doesn't describe whether there is any way to specify the desired type in either the test or the feature file.

**Comment by pcn** [comment]
So it's defined in `gherkin-rust` as:
```
/// A data table
#[derive(Debug, Clone, TypedBuilder, PartialEq, Hash, Eq)]
pub struct Table {
    /// The rows of the data table. Each row is always the same length as the first row.
    pub rows: Vec<Vec<String>>,
    /// The `(start, end)` offset the table directive was found in the .feature file.
    #[builder(default)]
    pub span: (usize, usize),
    /// The `(line, col)` position the table directive was found in the .feature file.
    #[builder(default)]
    pub position: (usize, usize),
}

impl Table {
    pub fn row_width(&self) -> usize {
        self.rows
            .iter()
            .next()
            .map(|x| x.len())
            .unwrap_or_else(|| 0)
    }
}
```

It'd still be helpful to have some examples of how it's best to use it, for us noobs.

**Comment by bbqsrc** [comment]
Ah, sorry I didn't get to this sooner!

Indeed, documentation on things like table usage is indeed lacking at the moment, though a lot of that perhaps comes from my historical lack of confidence in its implementation. :smile:

Will put out a new release soon that is in many ways a bit more of a blank slate, with integration of first-class async support as a core deliverable, and the removal of the `cucumber!` macro, so I'll hopefully get to documenting some table patterns when I get there.

Thanks for persevering, I hope to make it easier to contribute soon. 👍

**Comment by pcn** [comment]
Gotcha. Looking forward the the future.

**Comment by tyranron** [comment]
@ilslv let's document this one too before releasing `0.10`.

**Comment by tyranron** [comment]
Now described in ["Features" chapter of the Book](https://cucumber-rs.github.io/cucumber/main/Features.html#scenario-outline-keyword).
