### ISSUE TITLE
Scenario outline doesn't error on an unknown placeholder

### ISSUE THREAD

**Issue by wucke13** [cucumber-rs/cucumber#82]
Hi, I head a placeholder with a typo in it, so that there was  not col in the Examples which provided a value for it. Still the feature file parsed without an error. This is unexpected IMO, I would wish for errors in the anyways very loosely syntax of features to be reported as strict as possible.

**Comment by privalou** [comment]
Hello! I would like to take this issue :)

**Comment by tyranron** [comment]
@ilslv please, re-check this.
