### ISSUE TITLE
Review and cleanly integrate proc-macro into base crate

### ISSUE THREAD

**Issue by bbqsrc** [cucumber-rs/cucumber#93]

**Comment by ilslv** [comment]
@bbqsrc Hello 👋 
I'm original implementor of proc-macro autowiring voodoo magic. If this issue somehow related to my work or you have some questions I'd be happy to help

**Comment by bbqsrc** [comment]
Hey @ilslv! Right now it's just a marker issue to remind me to make the proc macro accessible from the primary cucumber crate, with a feature flag or similar.

Will let you know if I have any issues. 😄

**Comment by tyranron** [comment]
Closing this as the whole thing has been changed since then. Feel free to reopen, if needed.
